### ISSUE TITLE
run composer after cloning a drupal 8 repo

### ISSUE THREAD

**Issue by crevillo** [Boran/docker-drupal#11]
Hi there and thanks for this cool work. 

I'm trying to get my code from my github repo. there i don't place vendor files, but when running a container like this i get an error saying i have no `vendor/autoload.php`

So, do i need to run composer install after cloning? 

Thanks.

**Comment by Boran** [comment]
I don't understand fully, what options are you passing to the container on creation?
The error happens on creation or running? Can you show some log outputs?

Composer is installed in the container, but is not used to actually install drupal.

**Comment by crevillo** [comment]
hi again. here's my command
```
docker run -td -p 8003:80 -e "DRUPAL_GIT_REPO=https://crevillo:*********@github.com/crevillo/tantacom-web" -e "DRUPAL_GIT_BRANCH=drupal-8" --name drupal8003 boran/drupal
```
That repo is public, so i guess you can do the same with your user and password

Then it starts the pulling
```
Unable to find image 'boran/drupal:latest' locally
latest: Pulling from boran/drupal
```
Next, i see logs and...
```
docker logs -f drupal8003 
00. -- /start.sh run date=20160519-1746 base image=boran/drupal Image date=2016-01-12, https://github.com/Boran/webfact, build status in /var/www/html/.start.sh.stat -----
01. setup apache
Enabling module rewrite.
Enabling module vhost_alias.
Enabling module headers.
To activate the new configuration, you need to run:
  service apache2 restart
Site 000-default already enabled
02. check mysql
03. Website not installed: there is no /var/www/html/sites/default/settings.php and no DB
04. check mysql environment
-- setup mysql inside the container
160519 17:46:09 mysqld_safe Logging to '/var/log/mysql/error.log'.
160519 17:46:09 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
Generated mysql root + drupal password, see /root/.my.cnf /mysql-root-pw.txt /drupal-db-pw.txt
     
04. setup drupal
-- download drupal
-- clone the drupal site from git, branch drupal-8
Initialized empty Git repository in /var/www/html/.git/
remote: Counting objects: 516600, done.
remote: Compressing objects: 100% (289/289), done.
remote: Total 516600 (delta 15296), reused 15198 (delta 15198), pack-reused 501113
Receiving objects: 100% (516600/516600), 113.84 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (367907/367907), done.
From https://github.com/crevillo/tantacom-web
 * [new branch]      dev        -> origin/dev
 * [new branch]      drupal-8   -> origin/drupal-8
-- git submodule and update
05. -- Installing Drupal with profile=standard site-name=My Drupal Site 
require(/var/www/html/vendor/autoload.php): failed to open stream: No[warning]
such file or directory autoload.php:14
PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/autoload.php on line 14
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: require(): Failed opening required
'/var/www/html/vendor/autoload.php'
(include_path='.:/usr/share/php:/usr/share/pear') in
/var/www/html/autoload.php, line 14
-- ERROR: drush site-install failed
drush site-install standard -y --account-name=admin --account-pass=admin --account-mail=root@example.ch --site-name=My Drupal Site --site-mail=drupal@example.ch --db-url=mysqli://drupal:HIDDEN@localhost:3306/drupal
```

As you see, when i clone my repo, my repo doesn't have the vendor autoload cause i use to ignore it...
and look like drush is expecting having it there.

Thanks!.

**Comment by Boran** [comment]
Yes so the drupal you pull down from your git is incomplete, but why do you not include the full distribution ?
As you say, drush is not happy when running the site install with files missing .

Sean Boran

**Comment by crevillo** [comment]
well, drupal example.gitignore tells you to ignore vendor... that's why it's not in my repository. 
There's no need to add vendor to git imho, as you're supposed to modify anything in that folder...

**Comment by Boran** [comment]
Well why not add it and try again? If that is the problem an issue would have to be raised in the core or drush queues?

**Comment by crevillo** [comment]
adding composer install before the checkout makes it work for me. looks same at https://github.com/geerlingguy/drupal-vm/issues/515

**Comment by Boran** [comment]
So after the git pull, one needs this?
if Drupal > 8.0 and ! -f composer.json then
  composer install

Want to test and submit a pull request? :-)

**Comment by crevillo** [comment]
tested on my env and works: no need to check for drupal version, imho, as we know drupal 7 and drupal 6 has no composer.json. 
checking for the existence of composer.json is exactly what i do. 
i'll try a pr tomorrow. 
Thank you!

**Comment by Boran** [comment]
Great. But, the same start.sh is used for D7 and D8.

**Comment by crevillo** [comment]
Yes. Just i think test for composer will be enough. Test for version won't
hurt either :)

**Comment by Boran** [comment]
Would like to follow up and close this issue, can you paste the code you use here please, if you can't do a pull request?

**Comment by Boran** [comment]
Closing, see three commits in February, e.g. 5c934d5

**Comment by josuevalrob** [comment]
Hello. 

I am facing the same proble, but i am not using docker. I had clone my working site from my local to my bitbucket repository. Now is already conned into the server and when I try to install it, I face the same problem. 

But I don't have the composer on the server. Lucky I will try to install it and solve the problem as you guy commented. 

Check it [here](https://www.drupal.org/node/2737773):
