### ISSUE TITLE
Some more issues while building. 

### ISSUE THREAD

**Issue by crevillo** [Boran/docker-drupal#12]
Hello again, here's my issue now. 
Cloned your repo, entered in the cloned folder and tried 

```
 docker build -t boran-docker-drupal .
```

Two things here. 
Drush can't be installed. it looks dev-master has some unmet dependencies. here's the output

```
Removing intermediate container 4856a4a0fb30
Step 6 : RUN curl -sS https://getcomposer.org/installer | php &&     mv composer.phar /usr/local/bin/composer &&     COMPOSER_HOME=/opt/composer composer --quiet global require drush/drush:dev-master &&     ln -s /opt/composer/vendor/drush/drush/drush /bin/drush
 ---> Running in 552868417dfb
All settings correct for using Composer
Downloading 1.1.1...

Composer successfully installed to: //composer.phar
Use it: php composer.phar
Your requirements could not be resolved to an installable set of packages.
The command '/bin/sh -c curl -sS https://getcomposer.org/installer | php &&     mv composer.phar /usr/local/bin/composer &&     COMPOSER_HOME=/opt/composer composer --quiet global require drush/drush:dev-master &&     ln -s /opt/composer/vendor/drush/drush/drush /bin/drush' returned a non-zero code: 2
```

I managed to fix this changing  
`COMPOSER_HOME=/opt/composer composer --quiet global require drush/drush:dev-master`
to
COMPOSER_HOME=/opt/composer composer --quiet global require drush/drush:8.*` 

but probably could be better the idea try to satisfy that unmet dep.

Once changed that and restarted the build, it stops add this https://github.com/Boran/docker-drupal/blob/master/Dockerfile#L119
Where do that `/files/drupal-7` folder is meant to be?

Thanks.

**Comment by Boran** [comment]
Great.

/files/drupal-7: see the "Building an image" part of the readme.
A copy if drupal7 is included in the image, so one can quickly create containers and  without having internet access.

> cd files
>   rm -rf drupal-7  # incase an old version is there
>   drush dl drupal 
>   mv drupal-7.* drupal-7 

I'll wait for your pull request with a summary of changes proposed.

**Comment by Boran** [comment]
Forgot about this, never received a pull request. Master branch updated, closing this Issue.
