### ISSUE TITLE
External Database

### ISSUE THREAD

**Issue by act2281** [Boran/docker-drupal#13]
Hi,

This is working great for me, thank you! One question, I want to provide a database for the container to use so that it's starting similar to live. Where do you put that / how can I get it to build with that database.

Thanks for the great script!

**Comment by Boran** [comment]
hi,

See the README, e.g. 

-e "MYSQL_HOST=10.1.1.1" -e "MYSQL_DATABASE=drupal_site1" -e "MYSQL_USER=drupal_site1" -e "MYSQL_PASSWORD=pass4drupal_site1"

**Comment by act2281** [comment]
Sorry I was meaning to provide an SQL file for it load in, that was it's all in the container but closely matchs my live site.

**Comment by Boran** [comment]
That is not provided for, you would have to do some coding yourself, e.g. in custom.sh

**Comment by act2281** [comment]
When i run the below command, I don't get any files in /var/www/html, when I look in the logs it says it initialized empty GIT repository, then it stops.

If I go into the container, and run git pull it works just fine (so I think my SSH keys are good). Any ideas what I have wrong or how i can debug this? 

docker run --privileged=true -td -p 8002:80 -e "DRUPAL_GIT_REPO=https://user@bitbucket.org/user/essa-painting.git" -e "DRUPAL_GIT_BRANCH=master" -e "DRUPAL_FINAL_CMD=curl --silent -o /tmp/cleanup1.sh https://raw.githubusercontent.com/Boran/webfact-make/master/scripts/cleanup1.sh && chmod 700 /tmp/cleanup1.sh" -e "DRUPAL_FINAL_SCRIPT=/tmp/cleanup1.sh" -v /root/boran-drupal/ssh/id_rsa:/root/.ssh/id_rsa -v /root/boran-drupal/ssh/id_rsa.pub:/root/.ssh/id_rsa.pub -v /root/boran-drupal/ssh/known_hosts:/root/.ssh/known_hosts --name drupal8002 boran/drupal

**Comment by Boran** [comment]
Remove the --silent? Look at the container logs?
