### ISSUE TITLE
Build Image Fails

### ISSUE THREAD

**Issue by adam3145** [Boran/docker-drupal#14]
When i try to fork and build the image i am getting an error that it's returning a non-zero code. Any ideas?

Your requirements could not be resolved to an installable set of packages.
The command '/bin/sh -c curl -sS https://getcomposer.org/installer | php &&     mv composer.phar /usr/local/bin/composer &&     COMPOSER_HOME=/opt/composer composer --quiet global require drush/drush:dev-master &&     ln -s /opt/composer/vendor/drush/drush/drush /bin/drush' returned a non-zero code: 2

**Comment by Boran** [comment]
Master branch updated, please try again.

**Comment by adam3145** [comment]
It's still failing for me, even when when I just run  docker run boran/drupal

**Comment by Boran** [comment]
What arguments are you using, works fine for me:
```
name=drupal8003
image=boran/drupal
docker run -d -t -p 8003:80  --name $name $image
docker logs -f $name
```

**Comment by adam3145** [comment]
When I fork the repo, without making any changes and I try to have it build, I get

Build failed: lstat files/drupal-7: no such file or directory
https://hub.docker.com/r/act360/act-dockerdrupal/builds/boksj3hc5gxclthphdzzuzx/

I want to include some extra things into it, like blackfire.io, as well as setting up magento sites.

Thanks for you ideas on this!

Adam

**Comment by Boran** [comment]
Ah, that is an easy one.
From the README, 'download a copy of drupal to a subfolder called files/drupal-7' this is to provide a default Drupal-7 copy in the image, if no version is specified during installation.
```
cd files
  rm -rf drupal-7  # incase an old version is there

  drush dl drupal 
  mv drupal-7.* drupal-7 
  # or
  wget http://ftp.drupal.org/files/projects/drupal-7.53.tar.gz
  tar xf drupal-7.53.tar.gz 
  mv drupal-7.53 drupal-7
  cd ..
```

Now I realise that at this stage D8 should probably be the default, but that is another issue ...

**Comment by adam3145** [comment]
Perfect thanks everything is working now! Thanks so much for your help and the great docker file setup.

Thanks,

Adam
