### ISSUE TITLE
rename DRUPAL_PASSWORD to MYSQL_PASSWORD

### ISSUE THREAD

**Issue by fjenett** [Boran/docker-drupal#2]
Hey, thanks for the image! One suggestion: i find the naming of the environment variable "DRUPAL_PASSWORD" for the mysql password confusing. I recommend renaming "MYSQL_PASSWORD" into "MYSQL_ROOT_PASSWORD" and "DRUPAL_PASSWORD" into "MYSQL_PASSWORD". That would be consistent with the official mysql docker image: https://registry.hub.docker.com/_/mysql/

https://github.com/Boran/docker-drupal/blob/master/start.sh#L35

**Comment by Boran** [comment]
That makes sense, could you create a pull request please ?

Sean

**Comment by Boran** [comment]
Updated image pushed to dockerhub too.
If you could verify/test, that would be appreciated.

**Comment by fjenett** [comment]
Looks good. Will test later.

**Comment by fjenett** [comment]
Two things i noticed:
- the README still has the old DRUPAL_PASSWORD
- MYSQL_DB should maybe also be renamed to reflect MYSQL_DATABASE in official mysql image

Still working on testing … my Macbook somehow has trouble running docker these days. Will report back once i have something.

**Comment by fjenett** [comment]
"Welcome to My Drupal Site" ... seemed to have worked fine now! Thanks!

**Comment by Boran** [comment]
fixed. Pushed the image to docker hub too.
test again please, then I'll tag this release as an initial 1.0. It breaks backwards compatibility.

**Comment by fjenett** [comment]
```
docker run -td -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=drupal -e MYSQL_USER=drupal -e MYSQL_PASSWORD=drupal --name drupal-mysql-test mysql

docker run -td -P --link drupal-mysql-test:db -e MYSQL_HOST=db -e MYSQL_USER=drupal -e MYSQL_DATABASE=drupal -e MYSQL_PASSWORD=drupal -e DRUPAL_VERSION=drupal-8.0.0-beta4 --name drupal-8-test boran/drupal

docker logs -f drupal-8-test
```

Ran fine. Thanks!

**Comment by Boran** [comment]
great. closing this issue.
