### ISSUE TITLE
add some way to run a final script at the end of the build

### ISSUE THREAD

**Issue by Boran** [Boran/docker-drupal#4]
boran/drupal docker image and webfact: add some way to run a final script at the end of the build.

DRUPAL_FINALCOMMAND is getting too short in the drupal UI, and it is not subject to any versioning

e.g. call it DRUPAL_FINAL_SCRIPT adapt start.sh in boran/drupal. The referenced script would be available somewhere under /var/www/html e.g. from a repo or module..

**Comment by Boran** [comment]
DRUPAL_FINAL_SCRIPT  added, see readme. An example usage that pulls down cleanup1.sh and runs it:
```
name=drupal8003
domain=webfact.example.ch
image=boran/drupal
docker stop $name; docker rm $name

docker run -d -t -p 8003:80  -e "DRUPAL_FINAL_CMD=curl --silent -o /tmp/cleanup1.sh https://raw.githubusercontent.com/Boran/webfact-make/master/scripts/cleanup1.sh && chmod 700 /tmp/cleanup1.sh" -e "DRUPAL_FINAL_SCRIPT=/tmp/cleanup1.sh"  --name $name $image
```

**Comment by Jbartsch** [comment]
gr :8ball: !
