### ISSUE TITLE
Possibility to install Nginx instead of Apache

### ISSUE THREAD

**Issue by vabue** [Boran/docker-drupal#5]
Hello, 
Great job on creating automated Drupal install!

Is it possible to use LEMP, not LAMP in the container?

**Comment by Boran** [comment]
Hi, 

No, its Apache specific- more out of habit I guess.
It's true that nginx would be less resource hungry and give smaller containers. 
It's non trivial to do the switch though (as I've build tools such as wefactory and CI containers around lamp... But, patches are welcome :)

Sean Boran
