### ISSUE TITLE
Using FROM boran/drupal in Dockerfile, subsequent RUN drush en -y [module] gets pm-enable needs higher bootstrap level error

### ISSUE THREAD

**Issue by joannbrereton** [Boran/docker-drupal#7]
I've been using your image to try to show an integration between angular and drupal.

It works well if I just start the image and then drush en -y ngapp, but when I try to use a Dockerfile that does the same thing, it fails with

```
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM boran/drupal
 ---> cfd7bc61f89c
Step 1 : RUN drush en -y ngapp
 ---> Running in c1ece4f85de6
Command pm-enable needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'en ngapp' could not be executed.                  [error]
The command '/bin/sh -c drush en -y ngapp' returned a non-zero code: 1
BAM-034083-JB:drupal brereton$ Command pm-enable needs a higher bootstrap level to run - you will   [error]
/
```

**Comment by Boran** [comment]
have you tried doing "cd /var/www/html;" before doing any drush commands?

**Comment by joannbrereton** [comment]
That didn't work.

```
BAM-034083-JB:drupal brereton$ docker build -t test/drupal .
Sending build context to Docker daemon 3.072 kB
Step 0 : FROM boran/drupal
 ---> cfd7bc61f89c
Step 1 : RUN cd /var/www/html && drush en -y ngapp
 ---> Running in a68ba9953f19
Command pm-enable needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'en ngapp' could not be executed.                  [error]
The command '/bin/sh -c cd /var/www/html && drush en -y ngapp' returned a non-zero code: 1
```

I can work around it with a CMD startup.sh that does drush en for everything I need however.

**Comment by Boran** [comment]
Ah yes. Drupal is not installed at that point, its needs to be done from start.sh. The way to do this is create a "custom.sh" and put your custom code there. The standard start.sh executes custom.sh if it finds it at the end of the installation.

Alternatively way of doing this is during the "docker run", you could use "DRUPAL_FINAL_CMD and DRUPAL_FINAL_SCRIPT", see the README.
